### PR TITLE
Remove button referencing compute_haswell

### PR DESCRIPTION
**Pull request by Mark-Powers**
Note: I was not able to test this change locally.

### CODE REVIEW

**Review by diurnalist — APPROVED** [review]
Approved, but we'll wait to deploy until next week.

**Comment by msherman64** [comment]
I will test and review today.

**Comment by msherman64** [comment]
@Mark-Powers @diurnalist 
Should we actually remove this button? There are haswells at TACC and NU, and EVL and IIT will be bringing them online as well. 
image

**Comment by diurnalist** [comment]
I think we agreed to not do this.

**Pull request closed without merging**
