### PR TITLE
Add new SSD and network hardware filters

### PR DESCRIPTION
**Pull request by willtholke**

### CODE REVIEW

**Comment by Mark-Powers** [comment]
Thank you @willtholke! Would you mind adding some screenshots of how this looks?

**Comment by willtholke** [comment]
Screen Shot 2022-11-18 at 10 20 42 AM
Screen Shot 2022-11-18 at 10 20 55 AM
Screen Shot 2022-11-18 at 10 21 07 AM

**Review by Mark-Powers — APPROVED** [review]
Looks great! Pretty simple code.

**Review by super-cooper — APPROVED** [review]
:shipit:

**Pull request merged**
